import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { motion, AnimatePresence } from 'framer-motion';
import './CartModal.css';
export default function CartModal({ isOpen, onClose, cartItems, totalAmount, onRemoveItem, onCheckout, }) {
    const handleOverlayClick = (e) => {
        if (e.target === e.currentTarget) {
            onClose();
        }
    };
    return (_jsx(AnimatePresence, { children: isOpen && (_jsx(motion.div, { className: "modal-overlay", onClick: handleOverlayClick, initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, transition: { duration: 0.3 }, children: _jsxs(motion.div, { className: "modal-content", initial: { x: '100%' }, animate: { x: 0 }, exit: { x: '100%' }, transition: { type: 'spring', damping: 25, stiffness: 200 }, children: [_jsxs("div", { className: "modal-header", children: [_jsx("h2", { children: "Shopping Cart" }), _jsx("button", { className: "modal-close-btn", onClick: onClose, children: "\u2715" })] }), _jsx("div", { className: "modal-body", children: cartItems.length === 0 ? (_jsx("div", { className: "empty-cart", children: _jsx("p", { children: "Your cart is empty" }) })) : (_jsxs(_Fragment, { children: [_jsx("div", { className: "cart-items", children: cartItems.map((item, index) => (_jsxs(motion.div, { className: "cart-item", initial: { opacity: 0, x: -20 }, animate: { opacity: 1, x: 0 }, transition: { delay: index * 0.1 }, children: [_jsxs("div", { className: "item-info", children: [_jsx("h3", { children: item.name }), _jsxs("p", { className: "item-quantity", children: ["Quantity: ", item.quantity] })] }), _jsxs("div", { className: "item-price", children: [_jsxs("span", { className: "unit-price", children: ["\u20B5", item.price] }), _jsxs("span", { className: "subtotal", children: ["Subtotal: \u20B5", (item.price * item.quantity).toFixed(2)] })] }), onRemoveItem && (_jsx(motion.button, { className: "remove-btn", onClick: () => onRemoveItem(item.id), title: "Remove item", whileHover: { scale: 1.2, rotate: 10 }, whileTap: { scale: 0.9 }, children: "\uD83D\uDDD1\uFE0F" }))] }, item.id))) }), _jsx("div", { className: "modal-divider" }), _jsxs("div", { className: "cart-total", children: [_jsx("h3", { children: "Total Amount:" }), _jsxs("span", { className: "total-amount", children: ["\u20B5", totalAmount] })] }), _jsxs("div", { className: "modal-actions", children: [_jsx(motion.button, { className: "continue-btn", onClick: onClose, whileHover: { scale: 1.05 }, whileTap: { scale: 0.95 }, children: "Continue Shopping" }), _jsx(motion.button, { className: "checkout-btn", onClick: onCheckout, disabled: cartItems.length === 0, whileHover: { scale: 1.05 }, whileTap: { scale: 0.95 }, children: "Proceed to Checkout" })] })] })) })] }) })) }));
}
